/**
 * Liste des 64 theatres cibles pour l'agenda bruxellois.
 * Les noms doivent correspondre exactement aux valeurs `theatre_nom` dans la base.
 * Mise a jour : ajouter / corriger les noms au fur et a mesure que les connecteurs
 * sont crees dans le pipeline.
 */
export const THEATRES_CIBLE: string[] = [
  // --- Theatres deja connectes via le pipeline (36) ---
  'Archipel 19',
  'Atelier 210',
  'Auditorium Jacques Brel',
  'Balsamine',
  'Beursschouwburg',
  'BRASS',
  'BRONKS',
  'CC Auderghem',
  'Cirque Royal',
  'CreaNova',
  'Espace Magh',
  'Halles de Schaerbeek',
  'Improviste',
  'Kaaitheater',
  'KVS',
  'Le 140',
  'Le Public',
  'Le Rideau de Bruxelles',
  'Marni',
  'Theatre des Martyrs',
  'Mercelis',
  'Montagne Magique',
  'Novum',
  'Ocean Nord',
  'Poche',
  'Theatre des Riches-Claires',
  'Theatre les Tanneurs',
  'Theatre Royal du Parc',
  'Theatre National Wallonie-Bruxelles',
  'Theatre de la Toison d\'Or',
  'Toone',
  'Theatre Royal des Galeries',
  'Varia',
  'W:Halll',
  'Zinnema',

  // --- Theatres a connecter (29 supplementaires pour atteindre ~64) ---
  'Wolubilis',
  'Espace Senghor',
  'Centre Culturel d\'Uccle',
  'La Bellone',
  'La Samaritaine',
  'La Soupape',
  'La Venerie',
  'Les Brigittines',
  'Maison de la Culture de Tournai',
  'Palais des Beaux-Arts (BOZAR)',
  'Studio Vaartkapoen',
  'Koninklijke Vlaamse Schouwburg',
  'Theatre de Poche',
  'Theatre de la Balsamine',
  'Theatre de la Place des Martyrs',
  'Theatre de la Vie',
  'Theatre du Meridien',
  'Theatre Flamand',
  'Theatre Jean Vilar',
  'Theatre Marni',
  'Maison des Cultures et de la Cohesion Sociale de Molenbeek',
  'CC Jacques Franck',
  'Theatre de Namur',
  'La Monnaie',
  'AB (Ancienne Belgique)',
  'Les Riches-Claires',
  'Magic Land Theatre',
  'Palace',
  'Forest National',
]
